Fix for sky
MissingReferenceException: The variable specularCube of AntonovSuitSky
doesn't exist anymore.
You probably need to reassign the specularCube
variable of the 'AntonovSuitSky' script in the inspector.